module.exports = {
  apps: [
    {
      name: 'etiquetas-api',
      script: 'node_modules/tsx/dist/cli.mjs',
      args: 'server/index.ts',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        API_PORT: '3010',
        WEB_PORT: '3000',
      },
      error_file: './logs/pm2-api-error.log',
      out_file: './logs/pm2-api-out.log',
      time: true,
    },
    {
      name: 'etiquetas-web',
      script: 'node_modules/tsx/dist/cli.mjs',
      args: 'server/web.ts',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        WEB_PORT: '3000',
        API_PORT: '3010',
        API_URL: 'http://127.0.0.1:3010',
      },
      error_file: './logs/pm2-web-error.log',
      out_file: './logs/pm2-web-out.log',
      time: true,
    },
  ],
};
